{
    "code": "EAI_AGAIN",
    "errno": -3001,
    "hostname": "postgres",
    "level": "error",
    "message": "Error during datasource initialization. getaddrinfo EAI_AGAIN postgres",
    "stack": "Error: getaddrinfo EAI_AGAIN postgres\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)",
    "syscall": "getaddrinfo"
}
{
    "code": "28000",
    "file": "auth.c",
    "length": 161,
    "level": "error",
    "line": "545",
    "message": "Error during datasource initialization. no pg_hba.conf entry for host \"172.59.192.187\", user \"admin\", database \"hhcsauthdb\", no encryption",
    "name": "error",
    "routine": "ClientAuthentication",
    "severity": "FATAL",
    "stack": "error: no pg_hba.conf entry for host \"172.59.192.187\", user \"admin\", database \"hhcsauthdb\", no encryption\n    at Parser.parseErrorMessage (/src/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/src/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/src/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/src/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
}
{
    "address": "127.0.0.1",
    "code": "ECONNREFUSED",
    "errno": -111,
    "level": "error",
    "message": "Error during datasource initialization. connect ECONNREFUSED 127.0.0.1:5432",
    "port": 5432,
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
    "syscall": "connect"
}
{
    "address": "127.0.0.1",
    "code": "ECONNREFUSED",
    "errno": -111,
    "level": "error",
    "message": "Error during datasource initialization. connect ECONNREFUSED 127.0.0.1:5432",
    "port": 5432,
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
    "syscall": "connect"
}
{
    "address": "127.0.0.1",
    "code": "ECONNREFUSED",
    "errno": -111,
    "level": "error",
    "message": "Error during datasource initialization. connect ECONNREFUSED 127.0.0.1:5432",
    "port": 5432,
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
    "syscall": "connect"
}
{
    "address": "127.0.0.1",
    "code": "ECONNREFUSED",
    "errno": -111,
    "level": "error",
    "message": "Error during datasource initialization. connect ECONNREFUSED 127.0.0.1:5432",
    "port": 5432,
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
    "syscall": "connect"
}
{
    "address": "127.0.0.1",
    "code": "ECONNREFUSED",
    "errno": -111,
    "level": "error",
    "message": "Error during datasource initialization. connect ECONNREFUSED 127.0.0.1:5432",
    "port": 5432,
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
    "syscall": "connect"
}
{
    "address": "127.0.0.1",
    "code": "ECONNREFUSED",
    "errno": -111,
    "level": "error",
    "message": "Error during datasource initialization. connect ECONNREFUSED 127.0.0.1:5432",
    "port": 5432,
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
    "syscall": "connect"
}
{
    "level": "error",
    "message": "Error during datasource initialization. The server does not support SSL connections",
    "stack": "Error: The server does not support SSL connections\n    at Socket.<anonymous> (/src/node_modules/pg/lib/connection.js:77:37)\n    at Object.onceWrapper (node:events:628:26)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
}
{
    "code": "ECONNRESET",
    "errno": -104,
    "level": "error",
    "message": "Error during datasource initialization. read ECONNRESET",
    "stack": "Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)",
    "syscall": "read"
}
{
    "code": "ENOTFOUND",
    "errno": -3008,
    "hostname": "db",
    "level": "error",
    "message": "Error during datasource initialization. getaddrinfo ENOTFOUND db",
    "stack": "Error: getaddrinfo ENOTFOUND db\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)",
    "syscall": "getaddrinfo"
}
{
    "code": "ENOTFOUND",
    "errno": -3008,
    "hostname": "db",
    "level": "error",
    "message": "Error during datasource initialization. getaddrinfo ENOTFOUND db",
    "stack": "Error: getaddrinfo ENOTFOUND db\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)",
    "syscall": "getaddrinfo"
}
{
    "code": "ENOTFOUND",
    "errno": -3008,
    "hostname": "db",
    "level": "error",
    "message": "Error during datasource initialization. getaddrinfo ENOTFOUND db",
    "stack": "Error: getaddrinfo ENOTFOUND db\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)",
    "syscall": "getaddrinfo"
}
{
    "code": "ECONNREFUSED",
    "level": "error",
    "message": "Error during datasource initialization.",
    "stack": "AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)"
}
{
    "code": "ECONNREFUSED",
    "level": "error",
    "message": "Error during datasource initialization.",
    "stack": "AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)"
}
{
    "code": "ENOENT",
    "errno": -4058,
    "level": "error",
    "message": "Error during datasource initialization. ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\cert\\key.pem'",
    "path": "C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\cert\\key.pem",
    "stack": "Error: ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\cert\\key.pem'\n    at Object.openSync (node:fs:581:18)\n    at Object.readFileSync (node:fs:457:35)\n    at startServer (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:72:21)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:86:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "syscall": "open"
}
{
    "code": "ENOENT",
    "errno": -4058,
    "level": "error",
    "message": "Error during datasource initialization. ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\ssl\\key.pem'",
    "path": "C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\ssl\\key.pem",
    "stack": "Error: ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\ssl\\key.pem'\n    at Object.openSync (node:fs:581:18)\n    at Object.readFileSync (node:fs:457:35)\n    at startServer (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:72:21)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:86:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "syscall": "open"
}
{
    "code": "ENOENT",
    "errno": -4058,
    "level": "error",
    "message": "Error during datasource initialization. ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\key.pem'",
    "path": "C:\\Users\\tjmcc\\source\\hhcsManager\\server\\key.pem",
    "stack": "Error: ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\key.pem'\n    at Object.openSync (node:fs:581:18)\n    at Object.readFileSync (node:fs:457:35)\n    at startServer (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:72:21)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:86:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "syscall": "open"
}
{
    "code": "ENOENT",
    "errno": -4058,
    "level": "error",
    "message": "Error during datasource initialization. ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\key.pem'",
    "path": "C:\\Users\\tjmcc\\source\\hhcsManager\\server\\key.pem",
    "stack": "Error: ENOENT: no such file or directory, open 'C:\\Users\\tjmcc\\source\\hhcsManager\\server\\key.pem'\n    at Object.openSync (node:fs:581:18)\n    at Object.readFileSync (node:fs:457:35)\n    at startServer (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:72:21)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:86:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "syscall": "open"
}
{
    "level": "error",
    "message": "User with email test10@yahoo.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test1000@yahoo.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test1001@yahoo.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email 1001@yahoo.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email 1001@yahoo.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test20@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test@gmail.com already exists, aborting."
}
{
    "code": "ECONNREFUSED",
    "level": "error",
    "message": "Error during datasource initialization.",
    "stack": "AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)"
}
{
    "level": "error",
    "message": "User with email test@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:47:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:88:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:48:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:89:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:48:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:89:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Router.use() requires a middleware function but got a Object",
    "stack": "TypeError: Router.use() requires a middleware function but got a Object\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\router\\index.js:469:13)\n    at Function.<anonymous> (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:227:21)\n    at Array.forEach (<anonymous>)\n    at Function.use (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\express\\lib\\application.js:224:7)\n    at setupExpress (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:48:9)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\server.ts:89:9\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "User with email test@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test900@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test90@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test94@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test2@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email test10@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.",
    "stack": "TypeORMError: Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1121:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.computeInverseProperties (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1111:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:158:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.build (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:157:25)\n    at ConnectionMetadataBuilder.buildEntityMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\connection\\ConnectionMetadataBuilder.ts:106:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:710:13)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.",
    "stack": "TypeORMError: Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1121:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.computeInverseProperties (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1111:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:158:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.build (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:157:25)\n    at ConnectionMetadataBuilder.buildEntityMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\connection\\ConnectionMetadataBuilder.ts:106:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:710:13)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.",
    "stack": "TypeORMError: Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1121:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.computeInverseProperties (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1111:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:158:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.build (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:157:25)\n    at ConnectionMetadataBuilder.buildEntityMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\connection\\ConnectionMetadataBuilder.ts:106:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:710:13)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.",
    "stack": "TypeORMError: Entity metadata for User#roles was not found. Check if you specified a correct entity object and if it's connected in the connection options.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1121:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.computeInverseProperties (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:1111:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:158:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataBuilder.build (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataBuilder.ts:157:25)\n    at ConnectionMetadataBuilder.buildEntityMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\connection\\ConnectionMetadataBuilder.ts:106:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:710:13)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "User with email mccaskillhld@yahoo.com already exists, aborting."
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling createUser()"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.",
    "stack": "TypeORMError: Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:310:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:304:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.",
    "stack": "TypeORMError: Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:310:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:304:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.",
    "stack": "TypeORMError: Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:310:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:304:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Class constructor BaseEntity cannot be invoked without 'new'",
    "stack": "TypeError: Class constructor BaseEntity cannot be invoked without 'new'\n    at new Lesson (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\enties\\lesson.ts:34:42)\n    at EntityMetadata.create (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata\\EntityMetadata.ts:568:23)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:211:47)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Class constructor BaseEntity cannot be invoked without 'new'",
    "stack": "TypeError: Class constructor BaseEntity cannot be invoked without 'new'\n    at new Course (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\enties\\course.ts:33:42)\n    at EntityMetadata.create (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata\\EntityMetadata.ts:568:23)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:211:47)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Class constructor BaseEntity cannot be invoked without 'new'",
    "stack": "TypeError: Class constructor BaseEntity cannot be invoked without 'new'\n    at new Course (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\enties\\course.ts:33:42)\n    at EntityMetadata.create (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata\\EntityMetadata.ts:568:23)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:211:47)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Class constructor BaseEntity cannot be invoked without 'new'",
    "stack": "TypeError: Class constructor BaseEntity cannot be invoked without 'new'\n    at new Lesson (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\enties\\lesson.ts:34:42)\n    at EntityMetadata.create (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata\\EntityMetadata.ts:568:23)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:211:47)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Class constructor BaseEntity cannot be invoked without 'new'",
    "stack": "TypeError: Class constructor BaseEntity cannot be invoked without 'new'\n    at new Location (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\enties\\location.ts:33:42)\n    at EntityMetadata.create (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata\\EntityMetadata.ts:568:23)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:211:47)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Class constructor BaseEntity cannot be invoked without 'new'",
    "stack": "TypeError: Class constructor BaseEntity cannot be invoked without 'new'\n    at new Lesson (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\src\\enties\\lesson.ts:34:42)\n    at EntityMetadata.create (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata\\EntityMetadata.ts:568:23)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:211:47)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.",
    "stack": "TypeORMError: Relation Role#user and User#roles both has cascade remove set. This may lead to unexpected circular removals. Please set cascade remove only from one side of relationship.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:310:23\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:304:34)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Data type \"Array\" in \"User.roles\" is not supported by \"postgres\" database.",
    "stack": "DataTypeNotSupportedError: Data type \"Array\" in \"User.roles\" is not supported by \"postgres\" database.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:136:31\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:128:18)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Data type \"Array\" in \"User.roles\" is not supported by \"postgres\" database.",
    "stack": "DataTypeNotSupportedError: Data type \"Array\" in \"User.roles\" is not supported by \"postgres\" database.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:136:31\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:128:18)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Data type \"string\" in \"User.roles\" is not supported by \"postgres\" database.",
    "stack": "DataTypeNotSupportedError: Data type \"string\" in \"User.roles\" is not supported by \"postgres\" database.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:136:31\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:128:18)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error during datasource initialization. Data type \"Array\" in \"User.roles\" is not supported by \"postgres\" database.",
    "stack": "DataTypeNotSupportedError: Data type \"Array\" in \"User.roles\" is not supported by \"postgres\" database.\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:136:31\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validate (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:128:18)\n    at C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:43:18\n    at Array.forEach (<anonymous>)\n    at EntityMetadataValidator.validateMany (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\metadata-builder\\EntityMetadataValidator.ts:42:25)\n    at DataSource.buildMetadatas (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:730:33)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DataSource.initialize (C:\\Users\\tjmcc\\source\\hhcsManager\\server\\node_modules\\src\\data-source\\DataSource.ts:263:13)"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "User with email admin@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "User with email admin@gmail.com already exists, aborting."
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling findUserByEmail()"
}
{
    "level": "error",
    "message": "Error calling createCourse()"
}
{
    "level": "error",
    "message": "Error calling findCourseByUrl()"
}
{
    "level": "error",
    "message": "Error calling createCourse()"
}
{
    "level": "error",
    "message": "Error calling createCourse()"
}
{
    "level": "error",
    "message": "Error calling createCourse()"
}
{
    "level": "error",
    "message": "Error calling updateLocaton()"
}
{
    "level": "error",
    "message": "Error calling updateLocaton()"
}
{
    "level": "error",
    "message": "Error calling updateLocaton()"
}
{
    "level": "error",
    "message": "Error calling updateLocaton()"
}
{
    "level": "error",
    "message": "Error calling updateLocaton()"
}
{
    "level": "error",
    "message": "Error calling deleteLocation()"
}
{
    "level": "error",
    "message": "Error calling deleteLocation()"
}
{
    "level": "error",
    "message": "Error calling deleteLocation()"
}
{
    "code": "ECONNREFUSED",
    "level": "error",
    "message": "Error during datasource initialization.",
    "stack": "AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)"
}
